# Generated by Django 5.2.4 on 2025-07-25 01:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('running', 'Running'), ('passed', 'All Passed'), ('failed', 'Some Failed'), ('error', 'Error')], default='running', max_length=20)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.IntegerField(blank=True, help_text='Duración en milisegundos', null=True)),
                ('total_tests', models.IntegerField(default=0)),
                ('passed_tests', models.IntegerField(default=0)),
                ('failed_tests', models.IntegerField(default=0)),
                ('skipped_tests', models.IntegerField(default=0)),
                ('playwright_config', models.JSONField(blank=True, default=dict)),
                ('executed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='TestSuite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del archivo de prueba', max_length=200)),
                ('file_path', models.CharField(help_text='Ruta del archivo', max_length=500)),
                ('description', models.TextField(blank=True, help_text='Descripción opcional')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'file_path')},
            },
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título del test', max_length=500)),
                ('status', models.CharField(choices=[('passed', 'Passed'), ('failed', 'Failed'), ('skipped', 'Skipped'), ('flaky', 'Flaky')], max_length=20)),
                ('browser', models.CharField(choices=[('chromium', 'Chromium'), ('firefox', 'Firefox'), ('webkit', 'WebKit'), ('msedge', 'Microsoft Edge')], max_length=20)),
                ('duration_ms', models.IntegerField(help_text='Duración en milisegundos')),
                ('retry_count', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('error_stack', models.TextField(blank=True)),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('annotations', models.JSONField(blank=True, default=list)),
                ('worker_index', models.IntegerField(blank=True, null=True)),
                ('started_at', models.DateTimeField()),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='testing_dashboard.testrun')),
                ('suite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing_dashboard.testsuite')),
            ],
            options={
                'ordering': ['started_at'],
            },
        ),
    ]
